name: Pinio.Clients.App to the Moon!

on:
  push:
    branches:
      - qa
env:
  AZURE_WEBAPP_NAME: pinioclientsappqa   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/ClientsApp'      # set this to the path to your web app project
  NODE_VERSION: '12.22.5'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
       uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install
        npm run build -- --prod
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
